### ISSUE TITLE
Portal Issue

### ISSUE THREAD

**Issue by Irithnu** [moo-man/FVTT-DD-Import#10]
I have noticed that when importing into Foundry VTT, all portals are automatically set as doors, even when the window asset is used in DungeonDraft.

Is this a known issue? 

Thanks.

![portal](https://user-images.githubusercontent.com/65688006/82505119-e4d3b980-9af4-11ea-972d-5d80e59fdd40.png)

**Comment by moo-man** [comment]
It is a known issue, but portals are portals and I have no way to interpret what they are meant to be used as. So closing this issue for now because it's not really fixable. Thanks for the report though.

**Comment by Irithnu** [comment]
Thanks for the quick response. That is understandable. 

Fantastic module, by the way!
