### ISSUE TITLE
Terrain wall import request

### ISSUE THREAD

**Issue by JustChris68** [moo-man/FVTT-DD-Import#102]
Request for enhancement - 
I know that walls can be tricky, but, if one were to use a specifically named asset for a wall, could the import routine flag them as say terrain walls on import?
It could be a handy work around by having custom wall assets in dungeondraft or other software a map designer can draw in..  a symbolic wall symbol, then one could edit the json off the dd2vtt after the fact and make the .png associated with it into a transparent png.  I can't code my way out of a paper sack, but know just enough that this sounds possible without breaking things or rewriting the whole thing.

**Comment by JustChris68** [comment]
![image](https://user-images.githubusercontent.com/51926350/144622821-c89ce5f4-e47a-4929-9116-2654cea30ac6.png)
I already use this to create invisible walls in DD and they show like this during creation so I can see where they are.  This would just let them be imported as terrain walls instead.

**Comment by moo-man** [comment]
Unfortunately this is not possible. The .dd2vtt file has 2 main things: the image, and a bunch of coordinates. There's no way to see what assets were used, and especially not their association with walls.

**Comment by JustChris68** [comment]
gotcha... I wasn't sure if they could be flagged on import, thank you for taking the time to respond though.. I didn't see it in the data file but was hoping I just missed something.  I can still use this to import invisible walls and just edit them into terrain walls after the fact.
