### ISSUE TITLE
Request: A way to add multiple files to one scene.

### ISSUE THREAD

**Issue by SalieriC** [moo-man/FVTT-DD-Import#11]
Having multiple scenes for different layers of the same map is tedious. Having a way to import multiple files which get imported next to each other (above, below or on the sides) would be great for maps where it is likely that PCs are on different layers at the same time (i.e. taverns, ships, etc.).

**Comment by m42e** [comment]
@moo-man is that possible in javascript with available libraries? Else I would provide YAT (yet another tool) to create such a file.

**Comment by m42e** [comment]
@SalieriC an intermediate solution https://github.com/m42e/dd2vtt-stick
