### ISSUE TITLE
Option to Allow Conversion Quality?

### ISSUE THREAD

**Issue by Volksters** [moo-man/FVTT-DD-Import#111]
At the moment there is no way to set the quality when it converts to .webp, I would like to propose a percentage of quality, like how they done it in DungeonDraft, for example.

**Comment by hogart** [comment]
The default quality for WebP images in [Canvas.toBlob method](https://developer.mozilla.org/docs/Web/API/HTMLCanvasElement/toBlob) is 0.8, if this [SO answer](https://stackoverflow.com/questions/57881985/canvas-toblob-quality) to be believed (but it seems close enough), and the compression artefacts start to be quite noticeable.

![With conversion](https://github.com/moo-man/FVTT-DD-Import/assets/138504/43763c2c-44a7-4b48-85d3-8f85210a60cd)
With conversion

![Without conversion](https://github.com/moo-man/FVTT-DD-Import/assets/138504/a5db08e3-8067-4f0b-a12d-2466d8e79257)
Without

The fast and dirty fix is to supply a higher number (I personally prefer 0.9, it's a nice trade-off with barely visible compression) in [line 253](https://github.com/moo-man/FVTT-DD-Import/blob/master/ddimport.js#L253).
