### ISSUE TITLE
Replace instead of adding new scene

### ISSUE THREAD

**Issue by xxlbug** [moo-man/FVTT-DD-Import#12]
Hi there,
thank you for your importer!

Would it be possible if i do an import and a scene with the same name exists, that your importer could replace it as an option?

I find myself tweaking maps a lot after i test it with a player token. For now i delete the current scene and import the dungeondraft file again to have only one scene with the right name.

Cheers

**Comment by moo-man** [comment]
I should be able to add a "replace existing scene" dialog fairly easily

**Comment by xxlbug** [comment]
Would be nice if you can add this.
To add: If there is no scene title in the importer window written, take the title of the file without the extension?

**Comment by moo-man** [comment]
Also a good suggestion 👍

**Comment by xxlbug** [comment]
> Also a good suggestion 👍

Man, you are FAST with your replies!

**Comment by moo-man** [comment]
Depends on when I see the email on my phone ¯\_(ツ)_/¯
