### ISSUE TITLE
Deprecation warning Foundry version 10 Build 286 (dd-import version 2.4.0)

### ISSUE THREAD

**Issue by CircuitMusicLabs** [moo-man/FVTT-DD-Import#122]
Details as in title
- Foundry version 10 Build 286
- dd-import version 2.4.0

When loading the Configuration and Setup page, I get the following warning (yellow bar):
"2 compatibility warnings detected with installed Packages. Consult your console log (F12) for details."

The Log provides these entries:
- [dd-import] The module "dd-import" is using "author" which is deprecated in favor of "authors"
- [dd-import] The module "dd-import" is using "name" which is deprecated in favor of "id"

Thanks for looking into this.

**Comment by AlbanT** [comment]
Easy to fix when you replace the `author` in module.json by:
`  "authors": [
    {
      "name": "Moo Man"
    },
	{
      "name": "m42e"
    },
	{
      "name": "jacquie"
    }
  ],`
