### ISSUE TITLE
Walls import doesn't work with Foundry 0.6.2

### ISSUE THREAD

**Issue by kunxin-chor** [moo-man/FVTT-DD-Import#13]
The map image is imported, but no walls or windows are imported.

**Comment by moo-man** [comment]
Are you a fortune teller? 👀 

Do you mean 0.6.1? Regardless, I cannot reproduce. Perhaps send me your dd2vtt file or dungeondraft file

**Comment by kunxin-chor** [comment]
Hi, thanks for taking a look at the file. You can find it here: https://drive.google.com/file/d/1tghecRMJ91rSHCCwAnOmWOh-zHslt7Ag/view?usp=sharing

**Comment by moo-man** [comment]
![image](https://user-images.githubusercontent.com/28637157/84050726-bc144680-a973-11ea-9a14-90b653a18fac.png)
Works fine for me, can you describe your process?

**Comment by moo-man** [comment]
Closing this due to lack of info. @kunxin-chor if you have more details please comment or reopen if necessary.
