### ISSUE TITLE
Foundry V11 - Proximity windows as default for import

### ISSUE THREAD

**Issue by Sphinx2k** [moo-man/FVTT-DD-Import#137]
Foundry V11 does have this nice new window feature where you can only look through if you get cloth enough to that window. This is the new default when a windows is created.  Changing the windows by hand when there are a lot is a bit annoying. 
I would like to see this as the default for imported maps too or an option to make it the default behavior.

**Comment by moo-man** [comment]
Closed in https://github.com/moo-man/FVTT-DD-Import/commit/fbf2bd64510986539136d51abb8d7a362258e968
