### ISSUE TITLE
Door/Wall types

### ISSUE THREAD

**Issue by xxlbug** [moo-man/FVTT-DD-Import#14]
Hi there,

you can define "block light" or "allow light" with dungeondraft doors. I translate these with  "door" and "window" respectivly.

A door in foundryvtt would be a wall of type door.
A window in foundryvtt could be an invisible wall (see/hear everything, can't move through).

Is it possible to differentiate between these types in your importer?

Cheers

Relates to #10 

![image](https://user-images.githubusercontent.com/1849886/83650153-4fd2c500-a5b8-11ea-86cb-3b5bf0fbf645.png)

**Comment by moo-man** [comment]
Nope, as described in #10 portals are portals and that's all the information I'm given

**Comment by xxlbug** [comment]
Just wanted to add some infos for other people looking at the same problem.

From the dungeondraft discord bug channel where i contacted the developer https://discordapp.com/channels/497079041678114816/681268546398847112/717796892146401333

Bottom line: The json property "closed" in dungeondraft v 0.9.2.1 was falsely named, it should be block/allow light. Currently there is no way to distinguish a door from a window or a grate etc.
