### ISSUE TITLE
Error on importing: "Error Importing: SyntaxError: Unexpected End of JSON Import"

### ISSUE THREAD

**Issue by mattimeo84** [moo-man/FVTT-DD-Import#142]
I downloaded a battle map from Patreon. The map dimensions are 320x400. I don't know the DPI. The file size is 522 MB. Tried uploading in Chrome (fully updated), through Forge, Foundry (v11.315), D&D (3.1.2), and DD-Import (3.0.0). When tried adding through Firefox (fully updated), I don't get the error, but the file never uploads regardless of how long I wait.

**Comment by moo-man** [comment]
522 MB is way outside the parameters of feasibility, both for this module and WebGL. You'll need to find some way to get the export at a more reasonable size.

**Comment by mattimeo84** [comment]
ok, good to know

**Comment by moo-man** [comment]
It would vary wildly on your situation and hardware, given you're on Forge is likely a lot less than someone locally hosting.

However if your map is over 16k in dimensions on either side, you're past the texture size limit of any consumer available GPU.

For reference, if your map used the default export settings, it's about 81k x 106k. If it used the more recommended 100dpi setting, it's about 32k by 40k. This assumes you meant 320 squares by 400 squares.
