### ISSUE TITLE
Open Doors Are Imported As Windows

### ISSUE THREAD

**Issue by bcwhite-code** [moo-man/FVTT-DD-Import#146]
I've just started with Foundry and Arkenforge.  I created a map that has some doors that are open by default which causes `"closed": false,` to be in the generated `.uvtt` file for the relevant "portals".  When imported into Foundry, these become walls with "proximity" light & sight restrictions and no "door" configuration.

```
door: game.settings.get("dd-import", "openableWindows") ? 1 : (door.closed ? 1 : 0), // If openable windows - all portals should be doors, otherwise, only portals that "block light" should be openable (doors)
light : door.closed ? CONST.WALL_SENSE_TYPES.NORMAL : CONST.WALL_SENSE_TYPES.PROXIMITY, 
sight : door.closed ? CONST.WALL_SENSE_TYPES.NORMAL : CONST.WALL_SENSE_TYPES.PROXIMITY,
threshold : door.closed ? {} : {attenuation : true, light : 10, sight : 10} 
```

It seems that `door.closed` being `false` makes it such that the `door` attribute is not set.

I can set "Openable Windows" to prevent the map from being broken (because the default-open doors aren't doors and thus don't allow movement) but the vision behavior isn't quite the same and the doors start closed instead of open.

In fairness, looking that general lack of information inside the `.uvtt` file, I don't see a way this can be fixed without completely removing the "window" functionality (which I'm not suggesting) but maybe there is something I'm not seeing...

**Comment by moo-man** [comment]
Well, as you've described, portals that block or allow light (open or closed) is the only way to distinguish windows and doors. I'm not really familiar with Arkenforge or if it adds any extra options in the uvtt file. 

If a door is opened by default, it still needs to be set as a door (closed in the uvtt file), and then just open the door once it's imported into Foundry. I don't really see any alternative so I'm going to close this, but if a solution comes around, feel free to reopen.

**Comment by bcwhite-code** [comment]
Since you mention it...  I've been talking with Nathan at Arkenforge to try to add some extensions to UVTT.  He's receptive to the idea but busy at the moment.  Here's the full thread on Discord:

https://discord.com/channels/512782783509430283/1286434247661326429

I have a patch to add support for this your Universal Importer but until there is something being output from Arkenforge, it's not worth adding as input here.

https://github.com/moo-man/FVTT-DD-Import/compare/master...rwbcwhite:FVTT-DD-Import:master
