### ISSUE TITLE
Dungeondraft Importer doesn't create Scene

### ISSUE THREAD

**Issue by nilskk** [moo-man/FVTT-DD-Import#15]
I have Foundry on a Raspberry Pi as Server running. When I try to make a scene from my pc using Dungeondraft Importer, it doesn't create the map. I think the problem is that it searches for a file on my pc but foundry is running on my Raspberry. Any idea how to fix this?

**Comment by moo-man** [comment]
Can you provide any error messages? Maybe a screenshot of your dialog before importing?

**Comment by jacobbridges** [comment]
Might be related to my issue #16. There are two http related errors in console:

1. POST http://localhost:30000/upload 400 (Bad Request)
    ```
    {"error":"Cannot read property 'hasPermission' of null"}
    ```
2. GET http://localhost:30000/worlds/scenes/<scene_name>/<image>.png 404 (Not Found)

**Comment by vindr20** [comment]
I'm also seeing this issue, also on a raspberry pi. What's weird is that when I first switched over to the pi (~3 weeks ago?), I could have sworn I tested this module and found that it worked for me.

Here's a screenshot of my import dialog box:
![ddimport_dialog](https://user-images.githubusercontent.com/67212516/85215064-dd444200-b338-11ea-8d01-a556c92aeab3.PNG)


And I'm seeing the following error in the console:

> (node:4872) UnhandledPromiseRejectionWarning: Error: User undefined does not have permission to upload files.
    at uploadFile (/home/pi/foundry/foundryvtt/resources/app/dist/views.js:1:13499)
(node:4872) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:4872) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by moo-man** [comment]
If you can contact me on discord and give me your game link I can maybe take a closer look.

Note that a bug in 0.6.3 prevents uploads, but I don't recall seeing this error message attributed to that so I doubt that's the issue.

**Comment by vindr20** [comment]
I guess I edited my post right as you responded, so sorry for the false alarm. It was an issue with 0.6.3. I discovered the upload bug a minute later when trying to work around my initial issue, and downgrading made DDimport work as expected.

**Comment by moo-man** [comment]
Closing this due to lack of info. @nilskk if you have any more details please comment or reopen if necessary.
