### ISSUE TITLE
Failed to create scene: cannot read property 'hasPermission' of null

### ISSUE THREAD

**Issue by jacobbridges** [moo-man/FVTT-DD-Import#16]
OS: Windows 10
Foundry Version: 0.6.1
DungeonDraft Version: 0.9.21
DungeonDraft Importer Version: 0.81

Attempting to import [this file](https://raw.githubusercontent.com/jacobbridges/sundry/master/boilerworks.dd2vtt) with [these configurations](https://i.imgur.com/WICVaoo.png) results in [these errors](https://i.imgur.com/PNZtKdy.png).

Console output from browser:

![screenshot](https://i.imgur.com/NWx6QzK.png)

**Comment by moo-man** [comment]
Do you also have a remote server like the other user?

**Comment by jacobbridges** [comment]
No sir, I'm hosting everything locally at the moment.

**Comment by moo-man** [comment]
Wait, does `worlds/scenes/...` exist? Shouldn't it be `worlds/boilerworks/scenes`?

**Comment by jacobbridges** [comment]
Fuck me. Thank you mr moo-man.
