### ISSUE TITLE
Dungeondraft Import button not showing up 

### ISSUE THREAD

**Issue by rokwar** [moo-man/FVTT-DD-Import#17]
Using foundry VTT 0.6.2 the import button is not showing up underneath the create scene/create folder options. Also using pathfinder 2nd edition system version 1.5.2.

**Comment by moo-man** [comment]
Just the basic troubleshooting: You have enabled the module in the world correct?

**Comment by rokwar** [comment]
I am that dumb, that was my issue. Thank you.
