### ISSUE TITLE
Double doors

### ISSUE THREAD

**Issue by Alexis-Grimm** [moo-man/FVTT-DD-Import#20]
There are ways to produce double doors, visually, in dungeon draft, however when imported they are imported as two separate side by side doors, I was wondering if it were possible to make it so that if there are two doors side by side that they merge on import. This isn't like a huge deal, just a minor issue. Thanks for the wonderful module either way!

**Comment by moo-man** [comment]
Huh, well, I've always preferred doing double doors with 2 actual doors anyway, I didn't know people may prefer them grouped. I think the only way to do this would be to merge all doors that are adjacent to each other, which I don't think is necessarily a good solution.

**Comment by Alexis-Grimm** [comment]
It's fine, I get it, I find that having multiple doors really messes up the lighting, it's not like it takes me longer than like 3 minutes to fix any double doors on the map (and also secret doors, but I know that limitation isn't really your problem so much as it is part of dungeon-draft) Thanks for the great module.

**Comment by moo-man** [comment]
Glad you like it! I'm curious how it messes up the lighting though? Never had any problems myself.
