### ISSUE TITLE
Implement s3 storage support

### ISSUE THREAD

**Issue by Hydroxi** [moo-man/FVTT-DD-Import#21]
Hey, just saw that LividLindy#3609 already coded an implementation:
https://gitlab.com/jacquie/fvtt-dd-import/-/blob/master/ddimport.js

She also pinged you: https://discord.com/channels/170995199584108546/513918036919713802/702192903438729306
Could you implement it in the  main version?

**Comment by moo-man** [comment]
Thanks, I somehow missed that ping.
