### ISSUE TITLE
[Feature Request] Auto-Populate Name Field if Blank

### ISSUE THREAD

**Issue by jpagett** [moo-man/FVTT-DD-Import#27]
Use the filename of the .dd2vtt file if the name field is left blank. 

Would streamline importing many maps.

**Comment by moo-man** [comment]
This actually already works, it just doesn't populate the field. If you import it'll take the name of the file.

**Comment by jpagett** [comment]
Huh -- I was getting an error stating the field name was blank. I'll try to replicate when I get a chance.
