### ISSUE TITLE
Walls and Lighting ok, but no background image?

### ISSUE THREAD

**Issue by brittonica** [moo-man/FVTT-DD-Import#28]
Hello! Tried a small test map with the Importer, but it's only loading the wall and lighting layers. No background image at all. Screenshots and the Error log from my console follow. Any idea what I've done wrong? 
Dungeondraft Importer Version 0.10
Foundry VTT Version 0.65
Original Dungeondraft Map: [https://imgur.com/oDKYIbe](url)
Map as it appears after importing to FVTT: [https://imgur.com/bJ4XfaE](url)

Error Log:

Failed to load resource: the server responded with a status of 400 (Bad Request)
2game:1 Not allowed to load local resource: file:///D:/AppData/Local/FoundryVTT/Data/worlds/aoa/scenes/Test.png
upload:1 Failed to load resource: the server responded with a status of 400 (Bad Request)
3game:1 Not allowed to load local resource: file:///D:/AppData/Local/FoundryVTT/Data/worlds/aoa/scenes/Test.png
foundry.js:10781 TypeError: Cannot read property 'orig' of null
    at BackgroundLayer.draw (foundry.js:31449)
    at Canvas.draw (foundry.js:10778)
    at async Scene.view (foundry.js:28924)
draw @ foundry.js:10781
settings-extender.js:89 Uncaught TypeError: Cannot read property 'ctrlKey' of undefined
    at settings-extender.js:89
    at Array.reduce (<anonymous>)
    at modifiersEqual (settings-extender.js:88)
    at eventIsForBinding (settings-extender.js:97)
    at Function.KeyBinding.eventIsForBinding (settings-extender.js:206)
    at index.js:9
upload:1 Failed to load resource: the server responded with a status of 400 (Bad Request)
game:1 Not allowed to load local resource: file:///D:/AppData/Local/FoundryVTT/Data/worlds/aoa/scenes/Test.png
foundry.js:10781 TypeError: Cannot read property 'orig' of null
    at BackgroundLayer.draw (foundry.js:31449)
    at Canvas.draw (foundry.js:10778)
    at async Scene.view (foundry.js:28924)
draw @ foundry.js:10781
settings-extender.js:89 Uncaught TypeError: Cannot read property 'ctrlKey' of undefined
    at settings-extender.js:89
    at Array.reduce (<anonymous>)
    at modifiersEqual (settings-extender.js:88)
    at eventIsForBinding (settings-extender.js:97)
    at Function.KeyBinding.eventIsForBinding (settings-extender.js:206)
    at index.js:9

**Comment by moo-man** [comment]
Does the upload succeed?

**Comment by brittonica** [comment]
Yes, but only the walls and lighting. No image at all. You can see the error message generated by FVTT in the second image.

**Comment by moo-man** [comment]
I mean specifically the file upload. Do you see the file in your data folder?

**Comment by brittonica** [comment]
No, it does not appear in my data folder. I have it pointing to the Scenes directory of my local world.

**Comment by moo-man** [comment]
Right, which falls under your Data folder.

Point is, do you see the file? Does `D:/AppData/Local/FoundryVTT/Data/worlds/aoa/scenes/Test.png` exist?

**Comment by brittonica** [comment]
Ah, that worked! I'm sorry I was so dense with that. Thanks for taking the time to help me out.

**Comment by moo-man** [comment]
Well, it's still an issue, because it should've automatically set, I'm not sure why it didn't

**Comment by grantmatson** [comment]
I had the same issue and was only able to resolve it by manually setting the background image as was suggest by moo-man

**Comment by brittonica** [comment]
Yeah, I’ve tried a few other maps, but I still need to manually add the background image in the Scene Configuration. I basically export the map twice from DD: first as Universal VTT and then again as a PNG. The Universal VTT seems to only upload to Foundry as dynamic lighting and doors, and generates errors. But using the PNG as the background image makes everything work fine.

**Comment by lendrick** [comment]
I'm using the 0.7 beta of Foundry VTT and ran into this issue.  I notice the compatibility for this module is only 0.6.5, so maybe other people are also using Foundry 0.7 and that's why they're having this error?

**Comment by brittonica** [comment]
I’m using 0.6.5. That said, I imported a map today, and it kinda worked. The background image was imported, but was both smaller than and severely misaligned with the walls/lighting. Fixable, so not too much of an issue.

**Comment by moo-man** [comment]
@brittonica that sounds like something went wrong with the pixels/sq. What was the square size you exported it as?

**Comment by lendrick** [comment]
I'm using the 0.7 beta of Foundry VTT and ran into this issue.  I notice the compatibility for this module is only 0.6.5, so maybe other people are also using Foundry 0.7 and that's why they're having this error?

**Comment by brittonica** [comment]
I was definitely the pixels, @moo-man. I exported at 70 pixels per, and imported as the same. But I believe the Foundry default background image size limits size to 4000x3000. I had to manually change that in the Scene Configuration to what my actual image was: 7000x7000. After doing that, everthing lined up fine.

**Comment by moo-man** [comment]
That's something else I need to fix then because it should match what you exported.

However, `But I believe the Foundry default background image size limits size to 4000x3000` I know that's definitely not the case, if I understand your meaning. I've used over 10k by 10k maps before.

**Comment by moo-man** [comment]
I've closed this but if there's still issues in 0.12 feel free to open a new issue.
