### ISSUE TITLE
Support for windows

### ISSUE THREAD

**Issue by DFreds** [moo-man/FVTT-DD-Import#29]
Currently, Dungeon Draft supports two window portals by default. DD-Import is importing them as doors. Could DD-Import import them as regular walls with perception restriction set to 'None' if the portal starts with 'Window'?

**Comment by DFreds** [comment]
Hmm, maybe import them as a wall without perception restriction if the portal starts with the term 'window' and the "allow light" is selected.

**Comment by moo-man** [comment]
This should already be supported. If a portal doesn't block light, it will be interpreted as a window (removing perception restriction in FVTT)

**Comment by DFreds** [comment]
It's not for me. It's importing them as doors with perception restrictions

**Comment by moo-man** [comment]
Could you try uninstalling the module and reinstalling?

**Comment by DFreds** [comment]
Just tried that, seems to mark the perception restriction correctly now, but still classifies the windows as doors then can be opened/closed. I don't know, maybe some people want that, but I'm treating windows as decoration.

**Comment by moo-man** [comment]
See PR #22 where we talked about that. I could see it implemented as an option whether to import them as doors or not.

**Comment by moo-man** [comment]
I've added an option in 0.12 to have windows be openable or not.
