### ISSUE TITLE
Downloading the module from foundry downloads a version without the last commit.

### ISSUE THREAD

**Issue by garr71** [moo-man/FVTT-DD-Import#30]
I was having the path slashes issue, then saw a fix was already pushed, checked my installed version yet it matched 0.10. Just to be sure i checked the ddimport.js and i did not have the changes. Deleted the module and re downloaded it and its the same. Also tried downloading through the manifest link and the same, version 0.10 without the path slash issue fix nor the compatible version update from the module.json

**Comment by moo-man** [comment]
Thanks, manifest was pointing to the wrong location, which I remember him telling me to fix but I guess I didn't :/
