### ISSUE TITLE
Cannot successfully import

### ISSUE THREAD

**Issue by Meerletalis** [moo-man/FVTT-DD-Import#31]
Friday July 24.  Successfully imported a couple vtt format files from Dungeondraft.  Suddenly, they would not import any longer.  I cannot even import the files saved and imported successfully earlier in the day.  Probably the nut behind the wheel.

**Comment by 424C414B45** [comment]
I've just installed Foundry on **Ubuntu 20.04** and I'm having this issue as well. 

The module version is **0.11**

When I select the map I'm trying to import which is a **.dd2vtt** file, and click "Import" the dialog closes but nothing happens. 

There is also no option for **.dd2vtt** in the "Image Extension" drop down. There are only options for **.png** and **.webp**.

Previously, I had a Windows 10 install and the module worked perfectly.

**Comment by Meerletalis** [comment]
That is the same issue... I am on Windows 10, so I do not think it is the OS.

**Comment by moo-man** [comment]
@424C414B45  @Meerletalis can you paste a screenshot of your import dialog

`There is also no option for .dd2vtt in the "Image Extension" drop down. There are only options for .png and .webp.`
.dd2vtt is not an image, it contains an image + wall/light data.

**Comment by Meerletalis** [comment]
![image](https://user-images.githubusercontent.com/40697436/89106416-4797da00-d3ef-11ea-91ad-5dd2b5889173.png)

It used to have an option to import the .dd2vtt.

**Comment by moo-man** [comment]
Your issue is that your path is absolute, when it needs to be relative to the foundry data location

I can't see your full path but delete everything before worlds. It should start with `worlds/.../...`

And just to be safe, set offset to 0.

**Comment by Meerletalis** [comment]
![image](https://user-images.githubusercontent.com/40697436/89106416-4797da00-d3ef-11ea-91ad-5dd2b5889173.png)

It used to have an option to import the .dd2vtt.

**Comment by Meerletalis** [comment]
Ahh.  I wonder what I did that blanked out the path so I filled it in incorrectly.  Thank you.

**Comment by moo-man** [comment]
I went ahead and closed with but if there's still an issue with 0.12, go ahead and open a new one.

**Comment by Meerletalis** [comment]
Sorry – I thought I closed it.  Only issue I can see is every time I restart the server now, the path goes back to blank and it must be typed in.

**Comment by moo-man** [comment]
Hm, I can't reproduce that either, what's the path you entered? Open a new issue if it persists.
