### ISSUE TITLE
Background image path erroniously prefixed with '/'

### ISSUE THREAD

**Issue by pdf** [moo-man/FVTT-DD-Import#32]
When importing a map, the background image path gets set to `/worlds/<worldname>/<imagename>`, and the leading `/` causes errors generating the scene thumb and loading the scene.

Simply removing the `/` fixes the issue, allowing everything to work as expected.

**Comment by pdf** [comment]
Actually, this might be a dupe of #26 but I believe this is the root cause.

**Comment by moo-man** [comment]
This wasn't an issue with the slash, something unrelated instead. Thumbnail generation can be sorta weird but I think it's fixed now.
