### ISSUE TITLE
Canvas text shrinks for all imported scenes

### ISSUE THREAD

**Issue by brbrainerd** [moo-man/FVTT-DD-Import#36]
When I switch to a scene imported via this module, most of the text on Foundry's canvas shrinks to less than its normal size, including text for the names of tokens, chat bubbles, etc.  This is under the Chronicles of Darkness game system with several other mods installed.  This problem does not occur for scenes I have created manually from within FoundryVTT.  

I went on to further test this module in a clean instance using the Simple World Building system and no other mods activated.  This bug also occurred there.

**Comment by moo-man** [comment]
Not sure what's going on here, I can't reproduce, can you provide a screenshot?

**Comment by brbrainerd** [comment]
Certainly.  In addition to the actor's names being shrunk many of the icons are as well.  That tiny grey spot over each the doorways is how small the door icons have become, and this bug also shrinks condition icons and even the informational text in the top right from Butler UX Suite:

![Screenshot - 8_30_2020 , 12_52_25 AM](https://user-images.githubusercontent.com/8242207/91651525-ca966980-ea5b-11ea-85e0-a8089730d72b.png)

**Comment by moo-man** [comment]
This is simply your grid size. If you didn't change anything in the export, it sets to 256px, which is rather large, and the UI scales with that. I would recommend you export at 100px, which is foundry's default.
