### ISSUE TITLE
Importer Won't Upload the VTT File On Local Machine

### ISSUE THREAD

**Issue by Damocles346** [moo-man/FVTT-DD-Import#37]
Hello,

Been using your module for a few months now with no problems. Love it, I would marry it if I could. But these last two weeks its been spitting errors and will not upload the VTT files. I do all my work on my local machine. 

![Foundry DungeonDraft Error Report](https://user-images.githubusercontent.com/63006232/91924195-f2b5e080-ec86-11ea-80c1-24a6c830b875.PNG)

**Comment by Damocles346** [comment]
Ok, I did some more poking at it, and what I found was that when it created the scene it was making the background image path the file path that you put in during the import dialogue box. I made a .jpg copy of the scene and uploaded that as the background. All the walls and everything else still match, so that's a work around for now I guess.

**Comment by Damocles346** [comment]
So this: 
![1](https://user-images.githubusercontent.com/63006232/91925345-a4eea780-ec89-11ea-81c2-ae89f8d9117a.PNG)

turns into this:

![2](https://user-images.githubusercontent.com/63006232/91925359-ad46e280-ec89-11ea-920a-b882151c30ee.PNG)

**Comment by moo-man** [comment]
Yeah, your path shouldn't be absolute, it should be relative to FoundryVTT data location. So it should start at `Maps`

If you download the most recent version, it should show this as an warning message. (you may not have gotten the update because of #33, which I'm still considering)

Also, never go full fidelity.

**Comment by Damocles346** [comment]
Oh I had the fidelity  slider set somewhere in the middle. I had been fiddling with it to see if it was the issue. 

I guess I don't know what you mean it should start at maps. I guess I'm still not clear on why it was working before, and is not working now. But I will experiment and see if I can get it fixed.

**Comment by Damocles346** [comment]
Ok I see. I truncated down the address to start with maps and it pulled the file up fine. Okay. That works now. Thank you!
