### ISSUE TITLE
Nothing happens when I click "Import."

### ISSUE THREAD

**Issue by Formalhautwear** [moo-man/FVTT-DD-Import#38]
Using FoundryVTT 0.6.6, and DungeonDraft 0.9.4.1. 

Absolutely nothing happens when I click "Import" in the dialog box. I've selected the correct file from DungeonDraft, The only thing that seems a little odd is that DD wants to export with a double file extension (.dd2vtt.png), so I tried removing the ".png") portion. Still nothing. Could this be a compatibility issue with mods?

Thanks!

**Comment by moo-man** [comment]
I've never seen a `.dd2vtt.png` issue, are you sure you're exporting it correctly? It sounds like you're adding on `.dd2vtt` to the filename but still exporting it as a png.

**Comment by Formalhautwear** [comment]
Nothing happened when it was a .dd2vtt.png, I just deleted the ".png" and nothing continued to happen.

**Comment by moo-man** [comment]
Right, but it's not actually a `dd2vtt` file. I don't think you exported it correctly if DD is appending `png`. That means it's a png.

**Comment by Formalhautwear** [comment]
Do you think it's a problem on the DD end? I selected the UniversalVTT export mode. The file that gets created is .dd2vtt.png for some reason.

**Comment by moo-man** [comment]
Ok, yeah that should export as just `.dd2vtt`. Can you upload the file somewhere so I can see it?

**Comment by Formalhautwear** [comment]
I'm glad you asked, because it turns out DungeonDraft is creating an empty file when I'm trying to get it to export. Looks like a problem on DD's end.

**Comment by Formalhautwear** [comment]
...yup, GridPPI issue in the DungeonDraft import. Works like a charm now. Thanks for your quick responses, and your patience with this n00b!
