### ISSUE TITLE
Massive amount of overlapping walls

### ISSUE THREAD

**Issue by moo-man** [moo-man/FVTT-DD-Import#4]
Had to change the extension to a supported format to upload
![Paprika_Heart dungeondraft_map](https://user-images.githubusercontent.com/28637157/77355195-07726d80-6d12-11ea-871f-32585fb11495.gif)

This map, when imported into foundry, has over 2.2k walls, when it should have barely 100 by my estimation. @m42e

**Comment by m42e** [comment]
Oh, dear, want to send me the file? I will have a look.
