### ISSUE TITLE
DungeonDraft Update Breaks Importing

### ISSUE THREAD

**Issue by AidanHilt** [moo-man/FVTT-DD-Import#40]
After updating to DungeonDraft to version 0.9.4.2, and uploading maps exported from that version, changes in the .d2vtt file format have made it so that attempting to upload those maps causes corruption in the entire world, issues that eventually forced us to reset the world. I may be able to work on a pull request for this issue.

**Comment by moo-man** [comment]
I haven't heard of this before so it sounds like something else is wrong. Please include your map file so I can test

**Comment by AidanHilt** [comment]
I can't upload it on here, do you have another method you'd like me to use?

**Comment by moo-man** [comment]
Any upload service such as drive, or send it to me on discord. Moo Man#7518

Additionally, there's no mention of changes to the file format, and in my personal testing there are no issues, so clearly something else is wrong.
