### ISSUE TITLE
Idea: Allow placed objects to block LoS

### ISSUE THREAD

**Issue by NateHawk85** [moo-man/FVTT-DD-Import#41]
I personally make liberal use of the Object tool within DungeonDraft to create forest scenes. It'd be super convenient if importing the scene into FoundryVTT would cause the trees to automatically have LoS walls.

I'm not sure if there's an ability to do that already or if it would need additional changes on Megasploot's end as well.

**Comment by m42e** [comment]
Hi @NateHawk85, 

As the json file contains only lights, doors and walls this is not possible on dd-import side, sorry.

- m42e
