### ISSUE TITLE
DD Import Issue

### ISSUE THREAD

**Issue by justinthejaguar** [moo-man/FVTT-DD-Import#42]
It appears that I am unable to upload maps with the site lines in ver 7.3 of Foundry VTT. It continues to operate correctly when I revert to 6.6

**Comment by moo-man** [comment]
Can you be more specific about the issue? what happens when you try? Any console errors?

**Comment by justinthejaguar** [comment]
Please close this. It seems like another module is causing DD not to run correctly when I try to import a DD map while running the program locally. It basically causes the program to pinwheel on mac. I loaded just the DD module in an isolated test env and it ran fine.

**Comment by moo-man** [comment]
Interesting, that warning message is helpful though, thanks.

**Comment by justinthejaguar** [comment]
Hi Moo-Man

I was able to identify that this issue is caused with an interaction between DF Scene Enhancement and DD Importer.

Thank you,

Justin Payton
justinthejaguar@gmail.com

**Comment by flamewave000** [comment]
This should be corrected with DF Scene Enhancement v2.0 in 0.7.4+
