### ISSUE TITLE
Roof and Overhead Tiles

### ISSUE THREAD

**Issue by Alexis-Grimm** [moo-man/FVTT-DD-Import#44]
So there is a module called roof and overhead tiles that creates a roof tile layer that becomes transparent when a player's token is under them. And dungeondraft just recently updated to provide a roof tool, is there any chance that dungeon draft imports could create roof tiles when that module is present?

**Comment by moo-man** [comment]
I don't think this is going to be possible. The module may provide that layer, but Dungeondraft still just exports an image.

**Comment by Alexis-Grimm** [comment]
Too bad, Thanks for the quick reply! Love the module!
