### ISSUE TITLE
Lights seem very bright on new map import

### ISSUE THREAD

**Issue by bergmannf** [moo-man/FVTT-DD-Import#46]
When I import a map into 0.7.5 the lights seem very bright:

![image](https://user-images.githubusercontent.com/357576/97104197-3ee33700-16b2-11eb-8309-6a0ea9260e8b.png)

As a comparison in Dungeondraft the same section looks like this:

![image](https://user-images.githubusercontent.com/357576/97104217-62a67d00-16b2-11eb-8b52-8f9d23f871b3.png)

I guess it has something to do with the new `tintAlpha` property - or me using the lights in DungeonDraft wrong.

Right now I am working around this with a little function I run in the developer console after importing the map:

```javascript
    function dimLights(tint = 0) {
        var allLights = canvas.lighting.placeables;
        var updateOperation = allLights.map(light => { return { _id: light.id, tintAlpha: tint} });
        canvas.lighting.updateMany(updateOperation);
    }
```

**Comment by m42e** [comment]
@bergmannf would you mind sharing the map file? So I could play around with it a bit?

**Comment by bergmannf** [comment]
I actually made a map with just the default assets (the example used some pay-for ones):

The contrast isn't as high, but I guess you can still tell the difference:

Imported:

![image](https://user-images.githubusercontent.com/357576/97815445-590ead80-1c8e-11eb-9cac-c7c2dcf2a0a1.png)

In dungeondraft:

![image](https://user-images.githubusercontent.com/357576/97815450-65930600-1c8e-11eb-96e2-235f8f05b1d0.png)

And the dungeondraft file:

[Test.dungeondraft_map.zip](https://github.com/moo-man/FVTT-DD-Import/files/5471761/Test.dungeondraft_map.zip)

And the VTT export file:

[testmap.dd2vtt.zip](https://github.com/moo-man/FVTT-DD-Import/files/5471760/testmap.dd2vtt.zip)

**Comment by m42e** [comment]
<img width="518" alt="Bildschirmfoto 2020-11-02 um 19 18 25" src="https://user-images.githubusercontent.com/2410802/97904007-3046f080-1d40-11eb-972f-445d55f7d3a9.png">
That's what I get after importing your file in 0.7.5 with only DD Import enabled.

**Comment by Nordiii** [comment]
I have no problems either.
Tested once without any extra modules and then with blitz's community lightning enabled.

**Comment by oestred** [comment]
I am seeing the same thing.  I am uploading a zip with the DD map file and the VTT export.  
It is lighter all around but a few more obvious places are if you look at the pit, one looks dark and one is lighter, the crystals look less clear in the imported map due to more light over them too, adn in general not the same. 

[light-issue.zip](https://github.com/moo-man/FVTT-DD-Import/files/5499093/light-issue.zip)

**Comment by oestred** [comment]
Here is a screenshot of only part of the map but look at the black pit and the orange crystal in them both and compare.

![after vtt](https://user-images.githubusercontent.com/74035873/98326678-5fb36280-1fb7-11eb-9167-7e0d7d24849b.png)
[Uploading light-issue.zip…]()

**Comment by oestred** [comment]
![in dd](https://user-images.githubusercontent.com/74035873/98326699-6e9a1500-1fb7-11eb-9e40-065c0061a31d.png)

**Comment by Nordiii** [comment]
I think I know the Problem.

When exporting with light sources the map the light is already baked in graphically. Now the crystal seems to have 2 light sources which will again lighten up the map.
Now we have a static light up on the map + 2 light sources = brighter than in DD.

This would be my guess.

**Comment by oestred** [comment]
That makes sense. I forgot to mention that I did try doing the VTT export with the lights off in dungeon draft. When I imported it into foundry it did not have the lights at all.
  Some people did say that how light is handled was changed in the latest foundry 0.7.5

**Comment by Nordiii** [comment]
@oestred disabling the lights won’t export the light sources as far as I know. So, this I more likely a DD issue, it would be nice if you could export light sources without baking the light into the map.
The best bet probably would be to export it with light source and the export it without as png whatever and edit the scene.

But I don’t know how it all works and this is just a guess, didn't have time to test it.

**Comment by oestred** [comment]
@Nordiii I think you are right. I assumed that The universal VTT file would translate the light into foundry and not show it from the picture. Instead, foundry is translating the light and adding it but the light in the picture is also remaining. I am new to foundry so I do not know if this is what the DD importer did before the most recent foundry  update or not. 
  On the DD discord they recommended either keeping the light in my map and manually deleting all the lights foundry adds  or not exporting with the lights and adding all the light with foundry. The latter would be hard because I used some subtle lights in places and it’s hard to find them all and  to re-create them all in foundry the same way.  So I might just go with the first option and delete all the light sources that foundry added. I think only downside would be with foundry not handle that lighting that extra light I added won’t show up further away than The normal dynamic light range, which probably is not a big deal. I’m not even sure if it would look any different.

**Comment by m42e** [comment]
You can still try to export to dd2vtt with lights on, then export the image only with lights off. 
import dd2vtt in foundry and replace the image with the later one. Which version of DD are you using? maybe this bug has been introduced recently.

**Comment by oestred** [comment]
@m42e ohhhh.   I will try that. That seems like a possible workaround. So when the current image is removed the light from it will remain and the wall settings remain when I add/replace the image without  the lights on it?
   I will try that tonight or in the morning tomorrow and let you know how it goes. I appreciate your ideas.

**Comment by oestred** [comment]
Using latest dungeon draft.  The .9.4.4

**Comment by m42e** [comment]
If you replace it in the scene settings the walls should be kept

**Comment by Nordiii** [comment]
You could technically use a macro to edit all light sources on the map.

They would need to have no bright light and their color should be nothing.

But this would make customization harder, the best approach would really be to export with lights and then without and replace the scene image.

```
canvas.lighting.placeables.forEach(value=> value.update({
    bright: 0,
    tintColor: "#000000",
    tintAlpha: 0
}))
```

**Comment by bergmannf** [comment]
Sorry for the late comment, but I think I found out it depends on the system you use:

I tried to import into two different systems now:

1. The Shadowrun5 system (here the lights come out too bright) -> https://github.com/smilligan93/SR5-FoundryVTT
2. The DND5e system (here the lights come out perfectly fine) -> https://gitlab.com/foundrynet/dnd5e

So it might not actually be related to the importer at all - I will see if I can find out if the shadowrun system does anything to light on it's own.

**Comment by m42e** [comment]
@bergmannf Interesting and strange. 
Could you try two more things?
- Creating lights with identical settings in both systems? 
- Move imported lights. Are they still as bright?

**Comment by m42e** [comment]
So no matter what it could get an issue with 0.7.6

> The Color Intensity slider for Ambient Light and Token emitted light sources now uses an exponential scale which improves the user experience by providing for more fine-grained calibration of lighting intensity level towards the lower-end of the intensity range. The appearance of your light sources will not change as a result of this change - but the value of that intensity on the slider will. For example, what was previously an "intensity 0.2" may now appear as an "intensity 0.45".

**Comment by oestred** [comment]
@bergmannf Interesting, I am using the DND5E system when I had the issues.

I did see the 0.7.6 released and an updated DND5E 0.9.9 also released.  After The Forge hosting updates later today to 0.7.6 I will update the DND5E and see if having the new versions changes anything  If not, I am going to try the importing with lights and then changing the image to the files without lights as mentioned above as a possible work around.  I'll post here how it goes.

**Comment by bergmannf** [comment]
I found the problem - the systems use different units for the grids.

![image](https://user-images.githubusercontent.com/357576/98447024-17648380-2122-11eb-8f49-1e4e845d37af.png)

Shadowrun is using 1 meter per grid scale, whereas DnD uses the default 5ft per Grid, so if I just set the scale to ft the lights make sense again.

Guess it was a classic layer 8 problem in the end.
I guess I can close the issue now, as I feel there is nothing wrong with the plugin.

**Comment by m42e** [comment]
@bergmannf I am a bit confused. I thought the position and range of lights will be in grid units in the dd2vtt file. Correct me if I am wrong @moo-man 
If not I think the configured Grid scale should be handled.

**Comment by Nedrapter** [comment]
Hello, i think I'm facing the same (or similar problem). Imported maps are way brighters and even when I export with lighting off from DD, it comes in with lighting on in FVTT
![what is this](https://user-images.githubusercontent.com/74311190/99774570-a310e380-2b16-11eb-883c-5c69c7d18f14.png)

**Comment by sladecraven** [comment]
Really annoying issue, i confirm the behavior.
At least, in GetLights function, the formula :

> tintAlpha: (0.2 * light.intensity)

Should be modified to take into account the non-linear intensity scale since 0.7.6. Maybe something like : 

> tintAlpha: (0.05 * light.intensity)

**Comment by oestred** [comment]
I've been doing the DD import and then removing all of the lights in Foundry so it looks normal.  Luckily Foundry has a delete all lights button.
  The map still looks good as the DD lights are in it, but obviously no actual transmitting light sources show for players then so they need their own light source still.
