### ISSUE TITLE
Feature - Roofs

### ISSUE THREAD

**Issue by DarKDinDoN** [moo-man/FVTT-DD-Import#47]
Hello,

With the latest version of Dungeon Draft, we can now create roofs!
That would be awesome if the importer can import roofs as single tiles for example.
This way we can manage the visibility of the roof and ever better, we can use the module https://github.com/VanceCole/roofs

**Comment by moo-man** [comment]
Not currently possible as far as I can tell, see #44

**Comment by DarKDinDoN** [comment]
@moo-man The idea it to be able to isolate the roofs from the rest of the map.
A simple tile for each roof would be awesome. Even without the Roofs module, it would be a nice feature for us GM to us.

**Comment by moo-man** [comment]
I understand, but dungeondraft's exporter exports 1 image, the whole map. I can't really do anything with that except use it as the map.

**Comment by DarKDinDoN** [comment]
Ok, make sense. Thank you for replying 👍
