### ISSUE TITLE
Windows are showing up as doors?

### ISSUE THREAD

**Issue by Sonny-Crockett** [moo-man/FVTT-DD-Import#48]
Its custom asset so I guess thats the issue? Anyone else having this issue?

**Comment by moo-man** [comment]
There is a setting that makes windows openable, did you check the module settings?

**Comment by Sonny-Crockett** [comment]
I saw the module settings but had that un-checked. I also saw it said "ignore light", I unchecked light in export, is there another place for that setting? I mean its working great and opening windows could make sense. I just would like to see if I can change it. Thanks! 

Did a couple more tests and still everything is a door. I can upload a file you want to see what I am working with.

**Comment by moo-man** [comment]
Is it treated as an actual physical door? with perception blocked? or an openable invisible wall?

**Comment by Sonny-Crockett** [comment]
![7099da3b-8ba9-42a0-98e3-f8db650c9ad9](https://user-images.githubusercontent.com/39606970/97711914-14b7bd80-1a94-11eb-8fee-740f179eec3f.png)

This is what I see. I am not sure the colors, but the symbol to open them is a door.

**Comment by moo-man** [comment]
You need to look at your door settings, if they "block light" they are seen as doors, otherwise windows

**Comment by Sonny-Crockett** [comment]
I finally found that setting, sorry it took me so long. I think that fixes it!

Thank you for your help!
