### ISSUE TITLE
Image not updated when re-importing

### ISSUE THREAD

**Issue by stinkytoe** [moo-man/FVTT-DD-Import#49]
Here's the steps to recreate:

- Create a map in dungeondraft and export to 'Universal VTT'
- Upload to a scene in foundry, using this addon
- Delete the scene in foundry
- Edit the background image in dungeondraft
- Upload again to a scene in foundry

The new scene will always use the background image from the first upload. 

I have not checked if the wall geometry updates or not. 

Is there a simple way to work around this? 

Would you consider this a behaviour bug, or am I mistaken on the expected behaviour?

**Comment by m42e** [comment]
Workarround: delete the file (you can do that where you also can select the image for the scene)

**Comment by stinkytoe** [comment]
Found the issue. It was being cached in the browser, not in foundry. (Crtl-F5 in chromium fixed the issue.) Please close appropriately. Thanks for the response.
