### ISSUE TITLE
DungeonFog support

### ISSUE THREAD

**Issue by Follpvosten** [moo-man/FVTT-DD-Import#55]
Hi!

I'm a developer at DungeonFog currently working on our VTT export format for Foundry.
To make implementing this easier and gain wider support faster, we've chosen to use a similar format that Dungeondraft has already established.

We are just starting with this and right now the only difference between our files and the ones from Dungeondraft is the file ending (.df2vtt instead of .dd2vtt). We would possibly like to contribute at least the change to add this format to the file selection dialog filter to this importer.

Since it would be a bit of a marketing issue to tell our users to "use the Dungeondraft importer", we've thought about how to work around this; there would be three options, that we would love to discuss with you:

* Your current importer (at least in the metadata) gets renamed to "Battlemap Importer", "DungeonFog/Dungeondraft Importer" or something similar - by this your importer would become more "universal" and could support two different map companies.
* You publish this module a second time, with only the name/description changed to "DungeonFog Importer"
* We (DungeonFog) create a downstream fork of this repo where we - for now - only change the name and the description, and we publish it as our own Importer (of course with credit going to the original developers). 

To keep it simple and move fast, we would probably start with the last approach, but we can contribute our minimal changes back to the upstream later.

Which of these options sounds the best to you (@ the developers of this importer)?

**Comment by moo-man** [comment]
This sounds great, as I believe the original intention of Sploot was other software adopt that format to be more universal (hence why he named it "Universal VTT").

I suppose Option 1 is best, I'm open to naming changes. Battlemap Importer is fine, but with only 2 applications using the format, perhaps Dungeondraft/DungeonFog Importer is better for now. I'm not sure.

**Comment by Follpvosten** [comment]
Given that the format is called Universal VTT, maybe calling it "Universal Battlemap Importer" or "UVTT Battlemap Importer" (ignoring the redundancy) would be the best option. It's ultimately up to you to decide tho.
Do you think it would be possible to release an update changing the name before january the 26th? I'm almost done with the first version of our exporter by now, and it would be great if we could release it and then directly point people to your importer,

Another question: We would like to extend the format to support windows in addition to doors (they would be invisible walls in Foundry). How would you prefer to get this data from an importer implementation perspective?
I could either add a boolean field (like "invisible") to the points in line_of_sight or the respective doors,
or I could add a new array to the root object (called something like "invisible_walls" or "windows") that contains data like in line_of_sight (but it would likely just be two points per window).
I think neither of these changes would break backwards compatibility, and they would be equally easy to implement on the export side, so the approach we take is fully up to your preference.

Thanks a lot for your time and support!

**Comment by moo-man** [comment]
Sure, the name can be changed by then.

Windows should already be supported, they are denoted, perhaps not very intuitively, by the `closed` property, if I recall. Dungeondraft has an option where a door can either block or not block light, and that corresponds to the `closed` property.

**Comment by Follpvosten** [comment]
Hi again!

What's the current state of changing the name and adding `.df2vtt` to the list of supported formats? We'll need this in a week from now, so it would be great if you could confirm that it's going to be done until then. If you'd prefer, I could also just create a pull request implementing these minimal changes, then you'd only have to release the new version.

Thanks once again!

**Comment by moo-man** [comment]
Sorry for the delay, that should certainly be doable, I'll try to get it done before the weekend (It's a small change but I have a ton of modules/systems under my belt so it can be difficult to keep it all in my head), although I'm happy to accept a PR. 

Changing the name and adding `.df2vtt` is the only change needed?

**Comment by Follpvosten** [comment]
Don't worry about it, we're all very busy.

Yes, only the changes you named, we haven't changed the format at all.
