### ISSUE TITLE
Line of Sight Loses Points

### ISSUE THREAD

**Issue by anlumo** [moo-man/FVTT-DD-Import#59]
When importing the attached document, note how the line of sight doesn't follow the walls. However, if you look at the JSON itself, the points are there.

I think what happens is that something is removing points when one of the associated lines is short, but that tolerance is very high, so not a lot remains of the wall. For example, the upper room has 18 points in the JSON, but only 15 points are imported. The lower room is even more simplified, it has 62 points in the JSON but only 27 are imported (most are lost in the arc walls I guess).
![oversimplified](https://user-images.githubusercontent.com/644763/105234126-0ea11c80-5b6b-11eb-8c65-e4d3a300049b.png)

(Had to change the extension of the dd2vtt file to txt to let github accept it as an attachment.)

[oversimplified.txt](https://github.com/moo-man/FVTT-DD-Import/files/5845281/oversimplified.txt)

**Comment by moo-man** [comment]
What happens when you increase the fidelity?

**Comment by anlumo** [comment]
Ah, that's what the slider does!
![highfidelity](https://user-images.githubusercontent.com/644763/105239754-30030800-5b6d-11eb-81e0-c8cf730901a9.png)

**Comment by moo-man** [comment]
Well, it's only intended for cave walls, but I guess its possible to accidentally apply to normal ones
