### ISSUE TITLE
Dynamic lights from dungeonfog get the wrong color in foundry

### ISSUE THREAD

**Issue by eXaminator** [moo-man/FVTT-DD-Import#65]
I created a small test map with a single light source which is configured as follows:

![image](https://user-images.githubusercontent.com/2758908/105768135-3a057c00-5f5c-11eb-8ede-5b04610fb1ac.png)

The light is imported as follows in foundry:
![image](https://user-images.githubusercontent.com/2758908/105768196-52759680-5f5c-11eb-8ab5-bc34691bb209.png)

I also think the light distance is wrong too.

**Comment by anlumo** [comment]
The color issue has already been fixed on the DungeonFog end.

**Comment by eXaminator** [comment]
Closed due to the fact that this will be fixed by the dungeonfog team.
