### ISSUE TITLE
Feature request: Use the dungeondraft_map json file to improve imports

### ISSUE THREAD

**Issue by caewok** [moo-man/FVTT-DD-Import#70]
More of a long-term feature request, understanding that this is hard. 

It looks like the .dungeondraft_map file is (more or less) a json file, and it contains information on the position of each object placed on the map. The information includes position, rotation, scale, resource file location, and layer. The map file also contains comparable information on roofs and on wall placement. This leads to some interesting possibilities for better imports into Foundry. In theory, one could import the underlying base map and add objects in a more native Foundry format, including:

1. Import objects as tiles. This could be useful as then the user could manipulate the map objects in Foundry. For example, moving around chairs due to player interaction. Downside: Might be overkill if there are lots of tiles on the map; might be nice to limit this in some fashion, and "burn in" most tiles to the map image; only import native tiles for a select group. Might also need to limit it to user-added resources like purchased Forgotten Adventure resources; not sure whether the creator of Dungeondraft would approve of importing included Dungeondraft resources as tiles. 
2. Roofs. Dungeondraft can already identify roofs, so taking the JSON information from the .dungeondraft_map file could allow integration of roofs with the roofs module (or possibly the Foundry 0.8.2 planned overhead tiles). 
3. Wall heights. One could infer intended wall heights by associating them with the layers in Dungeondraft. This could allow importing walls with heights already set, for the wall height module.
4.  Lights. Right now, importing a dungeondraft map "burns in" the light effects to the map, which is not always desirable. (For example, turning off the light does not remove the burned-in light effect from the map.) Relying on the map file JSON might improve light imports, by using the base map and just adding the light separately.
5. Layers. If [Foundry Issue #4137](https://gitlab.com/foundrynet/foundryvtt/-/issues/4137) is resolved, this might again permit modules to add layers to the map. One could then correspond certain user-defined layers in Dungeondraft with layers in Foundry. For example, allowing the user to import a first- and second-story layered map as two distinct layers in Foundry.

Just a thought, and you may well have already looked into this possibility and encountered numerous obstacles. Thanks for all your work on this import tool!

**Comment by moo-man** [comment]
Thanks for the suggestion, this is how the importer used to work (before dd2vtt format), however I don't think it's going to go back. 

1. This would require uploading possibly hundreds of assets to the user data location, something that would lengthen the already considerable upload time, and be prone to failure. This is assuming I can get the assets used, as far as I'm aware, they're within a `.dungeondraft_pack` file.
2. This isn't really possible either, as roofs aren't a static image, I'm guessing they're with some sort of compositing of various images in dungeondraft, and even if it was possible to replicate it, I don't have access to the assets used, as above.
3. Possibly, but I think this bit of fidelity is just overkill, and will probably be prone to misinterpretations and errors
4. You can turn off the lights in the export, which does remove the light and its effects from the map. This also doesn't really relate to `dungeondraft_map` files, which don't include the image itself (like dd2vtt), so you still need to export the image from dungeondraft. 
5. This doesn't require .`dungeondraft_map` files, and the existing multiple-document upload can be reconfigured to do this.
