### ISSUE TITLE
Map objects are not imported as tiles or tokens, but as part of background image

### ISSUE THREAD

**Issue by Merudo** [moo-man/FVTT-DD-Import#75]
After importing a .dd2vtt file into Foundry, the individual objects are not longer selectable as individual tile or tokens.

It's as if the various objects were merged together into a single giant picture, instead of kept as separate tiles.

This is very odd behavior, and leads to unmodifiable maps that can be gigantic in size, as they do not properly take advantage of the assets being reused multiple times.

The importation of Dungeondraft should preserve object information, so that each individual object is kept separate and modifiable.

**Comment by moo-man** [comment]
This is how Dungeondraft exports work, they export as an image, not a composite of multiple images. If you want to utilize tiles, you'll have to upload the assets directly and place them as tiles.
