### ISSUE TITLE
Module is not importing the cave walls at all.

### ISSUE THREAD

**Issue by jarchiepacheco** [moo-man/FVTT-DD-Import#9]
Hello, I was working on my own recreation of the Mountain's Toe Gold Mine from the Dragon of Icespire Peak adventure for D&D 5e. I made the map I was happy with in DungeonDraft and when i used the module to import the vtt file it's not including the outline of the cave. In some instances it will add the walls in for parts of the cave that are inside the larger cave. 

Example
![image](https://user-images.githubusercontent.com/5483258/80924074-e2731080-8d3b-11ea-892d-5a06ee1cc39e.png)

It also is including any regular walls that I build into the map myself. Just not the cave ones. 
![image](https://user-images.githubusercontent.com/5483258/80924118-0a627400-8d3c-11ea-9d0e-3c32b1625f9a.png)

I am running version 0.5.5 of FoundryVTT and version 0.711 of the module. If it's important my version of dungeondraft is 0.9.1.2.

I also tried increasing the fidelity on the import to the maximum possible and that didn't make a difference.

**Comment by moo-man** [comment]
Question: what's the offset value?

**Comment by jarchiepacheco** [comment]
Oh wow that fixed it. I was originally leaving it blank because that worked for all of the other imports that weren't caves. Setting it to 0 fixed the problem. Thanks!

**Comment by moo-man** [comment]
Cool, this seems to be a common issue so I'm releasing some resiliency in that respect, thanks for the report though!
