### ISSUE TITLE
Feature Request: Option to automatically put Dungeondraft roofs on the foreground layer.

### ISSUE THREAD

**Issue by LebombJames** [moo-man/FVTT-DD-Import#91]
I don't know how easy this is (or if it's even possible), but this would make exporting maps with roofs that conceal buildings much easier.

**Comment by m42e** [comment]
This would not help, because the file contains only one image, and the image is the view from top, including the roofs.

**Comment by LebombJames** [comment]
Ah I see, I thought .dd2vtt kept the map in "pieces" so to speak, and the importer constructed them together.
