### ISSUE TITLE
Universal Battlemap Importer Not Creating Scene

### ISSUE THREAD

**Issue by Sonzilber** [moo-man/FVTT-DD-Import#93]
The issue that I'm experiencing is that when I'm importing my .dd2vtt files it goes through the dialogue, but doesn't create the scene.  This is only happening with two of my maps.  Both the file sizes are under 10mb.  It uploads the .webp file to my asset library successfully.

**Comment by Sonzilber** [comment]
I tried recreating a portion of one of the maps and I ran into the same issue with the other two.  I've also tried reducing the PPI down to 75 and it didn't work either.

**Comment by m42e** [comment]
Could you open the JavaScript console and look for errors there?

**Comment by Sonzilber** [comment]
This is the error message I got:
data.mjs:382 Uncaught (in promise) Error: Invalid WallData coordinates provided which must be a length-4 array of finite numbers
    at WallData._validateField (data.mjs:382)
    at WallData.validate (data.mjs:273)
    at new DocumentData (data.mjs:48)
    at new WallData (data.mjs:1953)
    at new Document (document.mjs:46)
    at new BaseWall (documents.mjs:1253)
    at new <anonymous> (foundry.js:9103)
    at new <anonymous> (foundry.js:8348)
    at new WallDocument (foundry.js:17156)
    at Function.makeWall (ddimport.js:541)
_validateField @ data.mjs:382
validate @ data.mjs:273
DocumentData @ data.mjs:48
WallData @ data.mjs:1953
Document @ document.mjs:46
BaseWall @ documents.mjs:1253
(anonymous) @ foundry.js:9103
(anonymous) @ foundry.js:8348
WallDocument @ foundry.js:17156
makeWall @ ddimport.js:541
GetWalls @ ddimport.js:526
DDImport @ ddimport.js:489
(anonymous) @ ddimport.js:338

**Comment by Sonzilber** [comment]
I got both of them to upload.  I set the offset to 0 and that seemed to work.

**Comment by m42e** [comment]
If you don't mind sharing the map I could have a look at it, even if I cannot promise when :)

**Comment by Sonzilber** [comment]
https://drive.google.com/drive/folders/1ZnFQ4diulLncEMmX_0BQiTd0VE6MTZml?usp=sharing
