### ISSUE TITLE
Import fails with Loading failed for worlds/undefined/

### ISSUE THREAD

**Issue by BastLeblanc** [moo-man/FVTT-DD-Import#99]
Failed to load resource: the server responded with a status of 404 ()
foundry.js:35541 Foundry VTT | Loading failed for worlds/undefined/xxx.webp (100%): undefined
_onError @ foundry.js:35541

Foundry 0.8.9
FVTT-DD-Import 2.2.0

**Comment by BastLeblanc** [comment]
user issue... 
In the import dialog, just edit correctly the "upload path" field to an existing folder

Leaving this issue in case it helps someone.

Maybe as a feature it could default to the current world?

**Comment by moo-man** [comment]
It used to, but 0.8 changed where the world name is stored and the importer needs to use the new location

**Comment by BastLeblanc** [comment]
But it's confusing as it was working in 0.7 without any custom path ...

**Comment by moo-man** [comment]
Right, as I said 0.8 changed where your world name is stored, used to be `game.world.name` (which the importer uses) and now it's `game.world.data.name` hence the undefined
